<?php
/**
 * Implements hook_menu_block_blocks().
 */
function submenu_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'submenu-1' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'submenu',
      'level'       => 1,
      'follow'      => active,
      'depth'       => 0,
      'expanded'    => 0,
      'sort'        => 0,
    ),
  );
}